config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout/:id', to: 'sessions#destroy'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:id/orders', to: 'users#orders'
  post '/sessions/:user_id/:item_id', to: 'sessions#add'
  delete '/sessions/:user_id/:item_id', to: 'sessions#remove'
  get '/sessions/:user_id/cart', to: 'sessions#cart'
  resources :orders, only: [:show, :new, :create, :update]
  resources :users, only: [:edit, :show, :update, :new, :create] 
  resources :locations, only: :index



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :order
    belongs_to :item
end
  

app/models/item.rb
class Item < ApplicationRecord
    has_many :coupon_items
    has_many :menus
    has_many :locations, through: :menus
end
  

app/models/location.rb
class Location < ApplicationRecord
    has_many :menus
    has_many :items, through: :menus
    has_many :orders
    has_many :users, through: :orders
end
  

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :item
    belongs_to :location
end
  

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :location
    has_many :carts
    has_many :items, through: :carts
end
  

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :orders

    validates :user_name, uniqueness: true
    validates :user_name, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :password, presence: true
    validates :password_confirmation, presence: true
    validates :email, presence: true
    validates :phone_number, presence: true
    validates :address_line_1, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zipcode, presence: true
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    
    def index
        @user = User.find_by_id(session[:user_id])
        @locations = Location.all
    end
  
  end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @user = User.find_by_id(session[:user_id])
    if params[:location]
      if params[:location][:id] != session[:location_id]
        session[:location_id] = params[:location][:id]
        session.delete @user.id
      end
    end
    @location = Location.find_by_id(session[:location_id])
  end

  def update
    order_id = params[:id].to_i
    @order = Order.find_by_id(order_id)
    @order.status = "cancelled"
    @order.save
    redirect_to "/orders/#{@order.order_number}"
  end

  def show
    @user = User.find_by_id(session[:user_id])
    @order = Order.find_by(order_number: params[:id])
    if session[:user_id] != @order.user_id
      flash[:message] = "You do not have access to this order"
      redirect_to new_order_path 
    end 

  end

  def create
    user_id = session[:user_id]
    location_id = session[:location_id].to_i
    status = "received"
    total_price = session[user_id]["total"]
    order_number = Time.now.to_s.delete(': -') + user_id.to_s
    @order = Order.create(user_id:user_id, 
      location_id:location_id, status:status, 
      total_price:total_price, order_number:order_number)
    session[user_id]["cart"].each {|item_id, quantity| 
      Cart.create(item_id:item_id, quantity:quantity, 
      order_id:@order.id) 
    }
    session.delete user_id
    redirect_to "/orders/#{@order.order_number}"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def home
  end

  def new
  end

  def cart
    if params[:user_id] != session[:user_id].to_s
      redirect_to new_order_path
      flash[:meesage] = "You do not have access to this cart"
    end
    @user = User.find_by_id(params[:user_id].to_i)  
  end

  def remove
    item_id = params[:item_id]
    user_id = params[:user_id]
    if session[:user_id] == user_id.to_i
      if session[user_id]["cart"][item_id]
        session[user_id]["cart"][item_id] -= 1
      else 
        session[user_id]["cart"].delete item_id
      end
      session[user_id]["total"] -= Item.find_by_id(item_id.to_i).price
    end
    if session[user_id]["total"] == 0
      session.delete user_id
      redirect_to new_order_path
    else
      redirect_to "/sessions/#{user_id}/cart"
    end
  end

  def add
    item_id = params[:item_id]
    user_id = params[:user_id]
    if session[:user_id] == user_id.to_i
      session[user_id] ||= {"cart" => {}}
      if session[user_id]["cart"][item_id]
        session[user_id]["cart"][item_id] += 1
      else 
        session[user_id]["cart"][item_id] = 1
      end
      session[user_id]["total"] ||= 0.0
      session[user_id]["total"] += Item.find_by_id(item_id.to_i).price
    end
    redirect_to new_order_path
  end

  def create
    @user = User.find_by(user_name: session_params[:user_name])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}"
    else
      if session_params[:user_name] == ""
        flash[:message] = "please enter a username"
      elsif session_params[:password] == ""
        flash[:message] = "please enter a password"
        flash[:user_name] = session_params[:user_name]
      else  
        flash[:message] = "We cannot find an account with this username and password"
        flash[:user_name] = session_params[:user_name]
      end 
      redirect_to '/login' 
    end
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

  private

  def session_params
    params.require(:user).permit(:user_name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id]
      @user = User.find_by_id(params[:id])
    else 
      @user = User.find_by_id(seesion[:user_id])
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def new
    if session[:user]
      @user = User.new(session[:user])
      session.delete :user
    else
      @user = User.new
    end
  end

  def create
    session[:user] = {}
    auto_fill(session[:user])
    @user = User.create(user_params)
    if @user.errors
      flash[:message] = @user.errors.messages
      redirect_to new_user_path
    else
      session[:user_id] = @user.id
      session.delete :user
      redirect_to @user
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
      User.find_by_id(params[:id]).destroy
      flash[:message] = "You have successfully deleted your account"
    redirect_to '/'
  end

  def orders
    @user = User.find_by_id(params[:id].to_i)
    @orders = @user.orders
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, 
      :user_name, :password, :password_confirmation, :email, 
      :phone_number, :address_line_1, :address_line_2, :city, 
      :state, :zipcode)
  end

  def auto_fill(user)
    user[:first_name] = params[:user][:first_name]
    user[:last_name] = params[:user][:last_name]
    user[:user_name] = params[:user][:user_name]
    user[:email] = params[:user][:email]
    user[:phone_number] = params[:user][:phone_number]
    user[:address_line_1] = params[:user][:address_line_1]
    user[:address_line_2] = params[:user][:address_line_2]
    user[:city] = params[:user][:city]
    user[:state] = params[:user][:state]
    user[:zipcode] = params[:user][:zipcode]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sliceline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="locations_page"><h1>Locations</h1>
<div id="home_button"><%= button_to "account home", @user, method: :get %></div>

<div class="locations">
<% @locations.each do |location| %>
    <div class="location"><h3><%= location.name %></h3>
    <div>Phone Nuber: <%= location.phone_number %></div>
    <div>Address:
    <div><%= location.address_line %></div>
    <div><%= location.city %>, <%= location.state %> <%= location.zipcode %></div></div>
    <div><%= form_for location, url: new_order_path, method: :get do |f| %></div>
        <%=f.hidden_field :id  %>
        <div><%=f.submit 'select location' %></div>
    <% end %></div>
<% end %>
</div></div>

app/views/orders/new.html.erb
<h1><%= @location.name %>'s Menu</h1>
<div id="home_button"><%= button_to "account home", @user, method: :get %></div>

<h3>Select another location: <%= form_for @location, url:new_order_path, method: :get do |f| %>
      <%= f.collection_select :id, Location.all, :id, :name %>
      <%= f.submit "change location", method: :get %>
  <% end %></h3>
  <div class="new_order"><div class="menu"><% @location.items.each do |item|%>
    <div class="menu_item">
    <div class="item_name"><%= item.name %></div>
    <div><%= item.description %></div>
    <div class="item_price">$<%= item.price %></div>
    <div><%= button_to "add to cart", "/sessions/#{session[:user_id]}/#{item.id}" %></div>
    </div>
<% end %></div>


<div><div class="cart"><% if session[@user.id] %>
    <%= "Items in your cart:" %><br>
    <% session[@user.id]["cart"].each do |item_id, quantity| %>
        <%= pluralize(quantity, Item.find_by_id(item_id).name) %><br>
    <% end %>
    Total $<%= session[@user.id]["total"] %>
    <%= button_to "checkout", "/sessions/#{@user.id}/cart", method: :get %>
<% else %>
    <%= "Your cart is empty" %>
<% end %></div></div></div>

<% if flash[:message] %>
    <%= flash[:message] %>
<% end %>

app/views/orders/show.html.erb
<div class="display_order_page"><h1>Order Number: <%= @order.order_number %></h1>
<div id="home_button"><%= button_to "account home", @user, method: :get %></div>

<h3>Order Status: <%= @order.status %></h3>
<div class="order_items">
    <% @order.carts.each do |cart| %>
        <div class="item">
        <div><% name = cart.item.name %></div>
        <div><% quantity = cart.quantity %></div>
        <div><% price = quantity * cart.item.price %></div>
        <div><%= "#{pluralize(quantity, name)} $#{price.round(2)}" %></div>
        </div>
    <% end %>
    <div class="total_price">$<%= @order.total_price.round(2) %></div>
</div>
<div class="navigation">
<div><%= button_to "return to order history", "/users/#{@order.user_id}/orders", method: :get %></div>

<div><% if @order.status == "received" %>
    <%= button_to "cancel order", "/orders/#{@order.id}", method: :patch %>
<% end %></div>

<div><%= button_to "place a new order", "/orders/new", method: :get %></div></div></div>

app/views/users/_form.html.erb
<div class="user_form"><%=form_for @user do |f| %>
    <%=f.label 'First Name' %>
    <%=f.text_field :first_name %><br>
    <%=f.label 'Last Name' %>
    <%=f.text_field :last_name %><br>
    <%=f.label :Username %>
    <%=f.text_field :user_name %><br>
    <%=f.label :Password %>
    <%=f.password_field :password %><br>
    <%=f.label "Confirm Password" %>
    <%=f.password_field :password_confirmation %><br>
    <%=f.label :Email %>
    <%=f.text_field :email %><br>
    <%=f.label 'Phone Number' %>
    <%=f.text_field :phone_number %><br>
    <%=f.label :Address %>
    <%=f.text_field :address_line_1 %><br>
    <%=f.text_field :address_line_2 %><br>
    <%=f.label :City %>
    <%=f.text_field :city %><br>
    <%=f.label :state %>
    <%=f.text_field :state %><br>
    <%=f.label :zipcode %>
    <%=f.text_field :zipcode %><br>
    <%=f.submit %>
<% end %></div>

app/views/users/edit.html.erb
<div class="edit_user_page"><h1>Edit User Profile</h1>
<div id="home_button"><%= button_to "account home", @user, method: :get %></div>

<%= render 'form' %>
<%= button_to "cancel", @user, method: :get, id:"cancel" %></div>

app/views/users/new.html.erb
<div class="new_user_page"><h1>Create User</h1>
<div class="form"><%= render 'form' %></div>
<div class="change_to_login">Already have an account?<%= button_to "login", login_path, method: :get %></div>
<div class="errors">
    <% if flash[:message] %>
        <% flash[:message].each do |message|%>
            <div><%= "#{message[0]} #{message[1][0]}" %></div>
        <% end %>
    <% end %>
</div>

app/views/users/orders.html.erb
<div class="order_history_page"><h1><%=@user.first_name %>'s Orders</h1>
<%= button_to "account home", @user, method: :get%>
<div class="user_orders">
<% @orders.each do |order| %>
    <div class="order_summary"><h3>Order Number: <%= link_to order.order_number, "/orders/#{order.order_number}" %></h3>
    <% order.carts.each do |cart| %>
        <div class="cart_item"><%= cart.quantity %> <%= cart.item.name %></div>
    <% end %>
    <div class="total">Total: $<%= order.total_price %></div></div>
<% end %>
</div></div>

app/views/users/show.html.erb
<div class="user_account_page"><h1><%= "Welcome #{@user.first_name}!" %></h1>
<div class="user_navigation">
    <div><%= button_to "Start a New Order", locations_path, method: :get %></div>
    <div><%= button_to "View Order History", "/users/#{@user.id}/orders", method: :get %></div>
    <div><%= button_to "Edit User Profile", edit_user_path, method: :get %></div>
    <div><%= button_to "Delete User Account", user_path, method: :delete %></div>
    <div><%= button_to "Logout", "/logout/#{@user.id}", method: :delete %></div>
</div>